name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Для Linux runners GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Debugging: Выводим содержимое репозитория, чтобы убедиться, что файлы правильно загружаются
    - name: List files in workspace
      run: ls -la

    # Настройка Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    # Кэширование зависимостей Maven
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Сборка с Maven
    - name: Build with Maven
      run: mvn clean install -B

    # Проверка версии Maven для отладки
    - name: Check Maven version
      run: mvn -v

    # Деплой WAR файла на Azure (для Linux App Service)
    - name: Deploy WAR to Azure
      run: |
        az webapp deploy --resource-group <ResourceGroup> --name <AppName> --src-path target/your-app.war --type war
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
