trigger:
- main  # Запуск пайплайна при пуше в ветку main

pool:
  vmImage: 'ubuntu-latest'  # Используем последнюю версию Ubuntu для CI/CD

variables:
  appName: 'JavaAA'  # Название приложения в Azure
  resourceGroup: 'JavaAA_group'  # Группа ресурсов в Azure
  azureSubscription: 'Azure for Students'  # Твоя подписка в Azure
  javaVersion: '11'  # Версия Java
  tomcatVersion: '9'  # Версия Tomcat (можно выбрать 9 или 10 в зависимости от нужд)
  packagePath: 'target/*.war'  # Путь к WAR файлу после сборки

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy to Azure'
  steps:
  - task: UseJavaToolInstaller@1
    inputs:
      versionSpec: '$(javaVersion)'  # Устанавливаем нужную версию Java
      addToPath: true

  - task: Maven@3
    displayName: 'Build with Maven'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      options: '-DskipTests=true'  # Можно настроить на выполнение тестов, если нужно
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'  # Указываем версию Java
      jdkArchitectureOption: 'x64'
      mavenVersionOption: 'Default'  # Используем стандартную версию Maven
      mavenAuthenticateFeed: false

  - task: AzureWebApp@1
    displayName: 'Deploy WAR to Azure Web App'
    inputs:
      azureSubscription: '$(azureSubscription)'
      appName: '$(appName)'  # Название твоего Azure App Service
      resourceGroupName: '$(resourceGroup)'  # Имя группы ресурсов
      package: '$(packagePath)'  # Путь к WAR файлу

  - task: AzureCLI@2
    displayName: 'Restart Azure Web App'
    inputs:
      azureSubscription: '$(azureSubscription)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp restart --name $(appName) --resource-group $(resourceGroup)  # Перезапуск приложения после деплоя
